class addClient_View(QWidget):
    def __init__(self):
        super(addClient_View, self).__init__()
        self.initUI()
    def initUI(self):
		self.gridLayout_2 = QtGui.QGridLayout(self)
        self.gridLayout_2.setObjectName(("gridLayout_2"))
        self.addClientName = QtGui.QHBoxLayout()
        self.addClientName.setObjectName(("addClientName"))
        self.nameLabel = QtGui.QLabel(self)
        self.nameLabel.setText(QtGui.QApplication.translate("addClientForm", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.nameLabel.setObjectName(("nameLabel"))
        self.addClientName.addWidget(self.nameLabel)
        self.nameLineEdit = QtGui.QLineEdit(self)
        self.nameLineEdit.setObjectName(("nameLineEdit"))
        self.addClientName.addWidget(self.nameLineEdit)
        self.gridLayout_2.addLayout(self.addClientName, 1, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(("verticalLayout"))
        self.clientHeader = QtGui.QLabel(self)
        self.clientHeader.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(("Waree"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.clientHeader.setFont(font)
        self.clientHeader.setText(QtGui.QApplication.translate("addClientForm", "Add Client", None, QtGui.QApplication.UnicodeUTF8))
        self.clientHeader.setObjectName(("clientHeader"))
        self.verticalLayout.addWidget(self.clientHeader)
        spacerItem = QtGui.QSpacerItem(17, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.clearButton = QtGui.QPushButton(self)
        self.clearButton.setText(QtGui.QApplication.translate("addClientForm", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setObjectName(("clearButton"))
        self.horizontalLayout.addWidget(self.clearButton)
        self.addClientButton = QtGui.QPushButton(self)
        self.addClientButton.setText(QtGui.QApplication.translate("addClientForm", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.addClientButton.setObjectName(("addClientButton"))
        self.horizontalLayout.addWidget(self.addClientButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 1)
